"""empty message

Revision ID: a4c367fb1fdf
Revises: 0fd7f93652f5
Create Date: 2021-04-03 13:55:58.638495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4c367fb1fdf'
down_revision = '0fd7f93652f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dates_battery', table_name='dates')
    op.drop_column('dates', 'battery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('battery', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('ix_dates_battery', 'dates', ['battery'], unique=False)
    # ### end Alembic commands ###
